/* Default values. Each one can be overridden from the dashboard (/admin/pages). */
export const pageMeta: Record<string, { path: string; label: string; headline: string; title: string; description: string }> = {
  accueil: { label: 'Accueil', headline: "Retrouver de la visibilité avant de fixer le cap.", path: '/', title: 'Calypso Advisory · Retrouver de la visibilité avant de fixer le cap', description: "Trésorerie tendue, créanciers pressants, décisions urgentes : Calypso Advisory aide les dirigeants à retrouver une lecture claire de leur situation, puis à piloter la suite." },
  audits: { label: 'Nos audits', headline: "Faire le point avant de fixer le cap.", path: '/audits', title: 'Nos audits', description: "Audit Juridique d'Orientation, Audit d'Évaluation, Audit Complet : une progression pour comprendre la situation avant de décider." },
  cockpit: { label: 'Cockpit Calypso', headline: "L'accompagnement pour retrouver le cap.", path: '/cockpit', title: 'Cockpit Calypso', description: "Un accompagnement humain dans la durée pour transformer les décisions en actions : priorités, trésorerie, échéances, créanciers, coordination des conseils." },
  approche: { label: 'Notre approche', headline: "Une méthode pour retrouver de la visibilité.", path: '/approche', title: 'Notre approche', description: 'Situer, orienter, prioriser, piloter : une méthode pour retrouver de la visibilité dans une situation complexe.' },
  professionnels: { label: 'Professionnels', headline: "Un partenaire pour vos dossiers les plus exigeants.", path: '/professionnels', title: 'Professionnels', description: 'Calypso intervient aux côtés des avocats, experts-comptables, administrateurs et directions financières sur les dossiers les plus exigeants.' },
  cabinet: { label: 'Le cabinet', headline: "Une équipe dédiée aux situations complexes.", path: '/cabinet', title: 'Le cabinet', description: 'Une équipe dédiée aux situations complexes, pour aider le dirigeant à rester maître de sa trajectoire.' },
  'faire-le-point': { label: 'Faire le point', headline: "Faire le point, avant de décider de la suite.", path: '/faire-le-point', title: 'Faire le point', description: 'Un premier échange confidentiel pour comprendre votre situation et identifier la prochaine étape utile. Réponse sous 24 heures ouvrées.' },
  mentions: { label: 'Mentions légales', headline: "Mentions légales", path: '/mentions-legales', title: 'Mentions légales', description: 'Mentions légales et données personnelles de Calypso Advisory.' }
};
