"""Import the validated single-file maquette into the Next.js project.

Run from the project root:  python3 scripts/import-maquette.py path/to/calypso-site.html
It regenerates: app/(site)/site.css, content/fragments.ts, public/legacy/site.js
Hash links (#audits) become real URLs (/audits); situation shortcuts become /faire-le-point?s=N.
"""
import json, re, sys, pathlib

src = pathlib.Path(sys.argv[1]).read_text(encoding='utf-8')
root = pathlib.Path(__file__).resolve().parent.parent

ROUTES = {'accueil': '/', 'audits': '/audits', 'cockpit': '/cockpit', 'approche': '/approche',
          'professionnels': '/professionnels', 'cabinet': '/cabinet', 'faire-le-point': '/faire-le-point',
          'mentions': '/mentions-legales'}

def links(html):
    html = re.sub(r'href="#([a-z-]+)"\s+data-sit-link="(\d+)"', lambda m: 'href="/faire-le-point?s=%s"' % m.group(2), html)
    html = re.sub(r'href="#([a-z-]+)"', lambda m: 'href="%s"' % ROUTES.get(m.group(1), '/'), html)
    return html

# CSS
css = src[src.index('<style>') + 7: src.index('</style>')]
(root / 'app' / '(site)' / 'site.css').write_text(css.strip() + '\n', encoding='utf-8')

# header (progress bar + header shell), footer
body_start = src.index('</style>')
first_main = src.index('<!-- ================= ACCUEIL')
header = src[body_start:first_main]
header = header[header.index('<div class="progress"'):]
footer = src[src.index('<footer'): src.index('</footer>') + 9]

# pages
pages = {}
for m in re.finditer(r'<main data-page="([a-z-]+)"( hidden)?>(.*?)</main>', src, re.S):
    pid = m.group(1)
    pages[pid] = '<main data-page="%s">%s</main>' % (pid, links(m.group(3)))

# the form now really sends: neutral notice, filled by the script
pages['faire-le-point'] = re.sub(r'<div class="notice" id="notice" role="status" hidden>.*?</div>',
    '<div class="notice" id="notice" role="status" aria-live="polite" hidden></div>', pages['faire-le-point'], flags=re.S)
# honeypot field against bots (visually hidden, not announced)
pages['faire-le-point'] = pages['faire-le-point'].replace('<div class="fields">',
    '<div class="hp" aria-hidden="true"><label>Site web<input type="text" name="website" id="website" tabindex="-1" autocomplete="off"></label></div>\n        <div class="fields">', 1)

frag = ['/* Generated by scripts/import-maquette.py from the validated maquette. Do not edit by hand. */']
frag.append('export const headerHtml = %s;' % json.dumps(links(header)))
frag.append('export const footerHtml = %s;' % json.dumps(links(footer)))
frag.append('export const pages: Record<string, string> = %s;' % json.dumps(pages, ensure_ascii=False, indent=0))
(root / 'content').mkdir(exist_ok=True)
(root / 'content' / 'fragments.ts').write_text('\n'.join(frag) + '\n', encoding='utf-8')

# script
scripts = re.findall(r'<script>(.*?)</script>', src, re.S)
js = scripts[-1]

router_start = js.index('  /* router */')
router_end = js.index("  menuBtn.addEventListener('click'")
new_router = r'''  /* pages are real URLs now: mark the current one in the menu, and pre-select a situation passed as ?s=N */
  (function(){
    var path = location.pathname.replace(/\/+$/, '') || '/';
    navLinks.forEach(function(a){ var h = a.getAttribute('href'); if(h === path && !a.classList.contains('btn')) a.setAttribute('aria-current', 'page'); });
    var q = /[?&]s=(\d)/.exec(location.search); if(q){ var r = document.getElementById('s' + q[1]); if(r) r.checked = true; }
  })();
  function go(id){ location.href = '/faire-le-point' + (pending !== null ? '?s=' + pending : ''); }
  [].forEach.call(document.querySelectorAll('[data-sit]'), function(b){ b.addEventListener('click', function(){ pending = b.getAttribute('data-sit'); go(); }); });
'''
js = js[:router_start] + new_router + js[router_end:]

js = js.replace('''  var copyBtn = document.getElementById('copyBtn');
  copyBtn.addEventListener('click', function(){''', '''  var copyBtn = document.getElementById('copyBtn');
  if(copyBtn) copyBtn.addEventListener('click', function(){''')

form_start = js.index("  document.getElementById('form').addEventListener('submit'")
form_end = js.index('  /* storm around')
new_form = r'''  (function(){
    var form = document.getElementById('form'); if(!form) return;
    var notice = document.getElementById('notice'), btn = form.querySelector('button[type=submit]'), busy = false;
    function say(msg, ok){ notice.textContent = msg; notice.hidden = false; notice.classList.toggle('ok', !!ok); notice.classList.toggle('ko', !ok); }
    form.addEventListener('submit', function(e){
      e.preventDefault(); if(busy) return;
      var nom = document.getElementById('nom'), mail = document.getElementById('mail'), ok = true;
      document.getElementById('err-nom').textContent = ''; document.getElementById('err-mail').textContent = '';
      if(!nom.value.trim()){ document.getElementById('err-nom').textContent = 'Indiquez votre nom pour que nous puissions vous recontacter.'; ok = false; }
      if(!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(mail.value.trim())){ document.getElementById('err-mail').textContent = 'Indiquez une adresse e-mail valide, par exemple nom@entreprise.fr.'; ok = false; }
      if(!ok){ (nom.value.trim() ? mail : nom).focus(); return; }
      var sit = form.querySelector('input[name=situation]:checked');
      var data = { situation: sit ? sit.value : '', message: document.getElementById('msg').value, nom: nom.value, societe: document.getElementById('societe').value, email: mail.value, telephone: document.getElementById('tel').value, website: (document.getElementById('website') || {}).value || '' };
      busy = true; btn.setAttribute('aria-busy', 'true'); btn.disabled = true; notice.hidden = true;
      fetch('/api/contact', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(data) })
        .then(function(r){ return r.json().catch(function(){ return {}; }).then(function(j){ return { ok: r.ok, j: j }; }); })
        .then(function(res){
          if(res.ok){ form.reset(); say('Merci. Votre demande nous est bien parvenue. Un membre de l\'équipe revient vers vous sous 24 heures ouvrées.', true); }
          else say(res.j && res.j.error === 'invalid' ? 'Certains champs ne sont pas valides. Vérifiez votre nom et votre adresse e-mail.' : 'L\'envoi n\'a pas abouti. Vous pouvez réessayer dans un instant, ou écrire directement à audit@calypso-advisory.com.', false);
        })
        .catch(function(){ say('L\'envoi n\'a pas abouti. Vérifiez votre connexion, ou écrivez directement à audit@calypso-advisory.com.', false); })
        .then(function(){ busy = false; btn.removeAttribute('aria-busy'); btn.disabled = false; });
    });
  })();

'''
js = js[:form_start] + new_form + js[form_end:]

assert js.rstrip().endswith('route();\n})();') or 'route();\n})();' in js
js = js.replace('  route();\n})();', '  onScroll();\n})();')
js = js.replace("window.addEventListener('hashchange', route);", '')

(root / 'public' / 'legacy').mkdir(parents=True, exist_ok=True)
(root / 'public' / 'legacy' / 'site.js').write_text(js.strip() + '\n', encoding='utf-8')
print('pages:', ', '.join(pages), '| css', len(css), '| js', len(js))
